# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-cloud-directory-sample

custom:
  webpack:
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline
# The `provider` block defines where your service will be deployed
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs6.10
  region: ap-southeast-2
  timeout: 15
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cognito-idp:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "clouddirectory:*"
      Resource:  [
        "arn:aws:clouddirectory:ap-southeast-2:687416365397:directory/AYfB6oMkbE5ysuMaEXwNa3s/schema/user/user_1"
      ]

# The `functions` block defines what code to deploy
functions:
  createGroup:
    handler: handler.createGroupObject
    events:
      - http:
          path: create-group
          method: get
          cors: true
  listApps:
    handler: handler.listApps
    events:
      - http:
          path: list-apps
          method: get
          cors: true
